#!/usr/bin/python3.11
import os
import argparse
import subprocess


def get_files_and_dirs(root_path):
    """Return the file and directory structure starting from the root_path."""
    structure = {}

    for root, _, files in os.walk(root_path):
        relative_root = os.path.relpath(root, root_path)
        structure[relative_root] = []

        for file in files:
            structure[relative_root].append(file)

    return structure


def get_entries_from_readme(readme_path):
    """Return a list of entries parsed from the README.md file."""
    cheatsheet_dir = r"."
    readme_structure = {cheatsheet_dir: []}

    if not os.path.exists(readme_path):
        return readme_structure

    with open(readme_path, "r") as f:
        content = f.read()
    title_id = content.index("#### cheatsheets\n")
    content = content[title_id:]

    newline_split = [
        line.split(" - ")[0].replace("`", "")
        for line in content.split("\n")
        if "*" in line
    ]

    last_dir = cheatsheet_dir
    for line in newline_split:
        line = line.split(" ")
        object_name = line[-1]
        if ".md" in object_name or ".sh" in object_name:
            readme_structure[last_dir].append(object_name)
        elif object_name[0].upper:
            readme_structure[object_name] = []
            last_dir = object_name

    return readme_structure


def find_missing_entries(structure, readme_structure):
    """
    Return a list of entries present in the structure
    but missing in the readme_structure.
    """
    missing_entries = {}

    for dir, files in structure.items():
        if dir not in readme_structure:
            missing_entries[dir] = files
        else:
            for file in files:
                if file not in readme_structure[dir]:
                    if dir not in missing_entries:
                        missing_entries[dir] = []
                    missing_entries[dir].append(file)

    return missing_entries


def print_missing_entries(missing_entries):
    """Print the missing entries in a readable format."""
    for dir, files in missing_entries.items():
        print(f"Directory: {dir}")
        for file in files:
            print(f" - Missing file: {file}")
        print()


def find_emtpy_files(structure):
    """Find files that have 0 lines"""
    small_files = []
    for dir in structure:
        if dir == ".":
            path = "./cheatsheets/"
        else:
            path = f"./cheatsheets/{dir}"

        for file in structure[dir]:
            file_len = subprocess.check_output(f"wc -l {path}/{file}", shell=True)
            file_len = int(file_len.decode("utf-8").split(" ")[0])
            if file_len <= 1:
                small_files.append((file, file_len))
    return small_files


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Verfify the validity of README.md")
    parser.add_argument(
        "-r",
        "--readme",
        type=str,
        default="README.md",
        help="Path to the readme file.",
    )
    parser.add_argument(
        "-s",
        "--small-files",
        action="store_true",
        help="Print files that have no content.",
    )

    args = parser.parse_args()

    root_dir = "./cheatsheets"
    structure = get_files_and_dirs(root_dir)

    if args.small_files:
        small_files = find_emtpy_files(structure)
        for file in small_files:
            print(f"{file[0]} has length {file[1]}")
    else:
        readme_structure = get_entries_from_readme(os.path.join("./", "README.md"))
        missing_entries = find_missing_entries(structure, readme_structure)
        print_missing_entries(missing_entries)
